# Production values for timewise-website
# Override default values for production deployment

replicaCount: 3

image:
  repository: timewise/timewise-website
  pullPolicy: IfNotPresent
  tag: "1.0.0"

serviceAccount:
  create: true
  automount: true

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "4173"
  prometheus.io/path: "/metrics"

podSecurityContext:
  fsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 4173

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: timewise.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: timewise-tls
      hosts:
        - timewise.example.com

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - timewise-website
          topologyKey: kubernetes.io/hostname

envConfigMap:
  NODE_ENV: "production"

