# Staging values for timewise-website
# Override default values for staging deployment

replicaCount: 2

image:
  repository: timewise/timewise-website
  pullPolicy: Always
  tag: "staging"

serviceAccount:
  create: true
  automount: true

service:
  type: ClusterIP
  port: 80
  targetPort: 4173

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  hosts:
    - host: staging.timewise.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: timewise-staging-tls
      hosts:
        - staging.timewise.example.com

resources:
  limits:
    cpu: 300m
    memory: 384Mi
  requests:
    cpu: 150m
    memory: 192Mi

autoscaling:
  enabled: false

envConfigMap:
  NODE_ENV: "staging"

